version: '3.8'

services:
  db:
    image: postgres:14.11-alpine3.19
    container_name: telegram_bot_postgresql
    hostname: telegram_bot_postgresql
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.2.5
    container_name: telegram_bot_redis
    hostname: telegram_bot_redis
    restart: always
    environment:
      REDIS_DATABASES: 16
      REDIS_PORT: ${REDIS_DB_PORT}
      REDIS_PASSWORD: ${REDIS_DB_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - ./redis/node-1/data:/data
      - ./redis/node-1/conf/redis.conf:/etc/redis/redis.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
