export enum ECommands {
  ADD_TEAM = 'ADD_TEAM',
  SEE_FAVORITES = 'SEE_FAVORITES',
  RESTART = 'RESTART',
  SETTINGS = 'SETTINGS',
}

export enum ECallbacks {
  COUNTRIES = 'COUNTRIES',
  COUNTRY = 'COUNTRY',
  COUNTRY_PAGE = 'COUNTRY_PAGE',
  LEAGUE = 'LEAGUE',
  TEAM = 'TEAM',
  SAVE_TEAM = 'SAVE_TEAM',
  REMOVE_TEAM = 'REMOVE_TEAM',
  TO_FAVORITE = 'TO_FAVORITE',
  FAVORITE_TEAM = 'FAVORITE_TEAM',
  TEAM_SQUAD = 'TEAM_SQUAD',
  TEAM_STATS = 'TEAM_STATS',
  TEAM_FIXTURES = 'TEAM_FIXTURES',
  FIXTURE_ODDS = 'FIXTURE_ODDS',
  FIXTURE_PRED = 'FIXTURE_PRED',
  FIXTURE_REMIND = 'FIXTURE_REMIND',
}

export enum ESettingsActions {
  SETTINGS = 'SETTINGS',
  SETTINGS_LANGUAGE = 'SET_LANGUAGE',
  SETTINGS_BET = 'SET_BET',
  SETTINGS_BOOKMAKERS = 'SET_BOOKMAKERS',
}
